language: node_js
sudo: required
node_js:
  - 12.9.1

# 指定缓存模块，可加快编译速度
cache:
  directories:
    - node_modules

# 指定博客源码分支，这里填入博客源码的分支名
branches:
  only:
    - hexo

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

# 设置 git push 别名，邮箱。替换真实 token 到 _config.yml 文件中，然后 deploy 部署
after_script:
  - git config user.name "Asutorufa"
  - git config user.email "mundanedefoliation@gmail.com"
  - git clone https://github.com/Asutorufa/Asutorufa.github.io.git .deploy_git # 解决 commit 清空问题
  - cd .deploy_git
  - git checkout master
  - cd ../
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GIT_REPO_TOKEN}/g" ./_config.yml # 这里的 GH_TOKEN 名字要和网页中定义的别名一致
  #- cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle 
