# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: アストルファの幻想郷
subtitle: やりたくないこともやる
description: アンドロイドです。
author: アストルファ
language: 
- en
- ja
- zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://Asutorufa.github.io/
root: /
permalink: posts/:abbrlink/ #:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: categorized ##uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next


# Deployment
## Docs:https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: #repository:
   github: https://gh_token@github.com/Asutorufa/Asutorufa.github.io.git
  branch: master

#站内搜索
search:
    path: search.xml
    field: post
    format: html
    limit: 10000

#站内地图
sitemap:
    path: sitemap.xml
    template: 
    rel: true
    tags: true
    categories: true

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# lazyload image
lazyload:
  enable: true
  onlypost: false
  loadingImg: 

filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: false
  css:
    # minify all css files
    minify: true
    # bundle loaded css file into the one
    bundle: false # 会导致页面加载变得很奇怪
    # use a script block to load css elements dynamically
    delivery: true 
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
      - '**/font-awesome.min.css'
  js:
    # minify all js files
    minify: true
    # bundle loaded js file into the one
    bundle: false  # 会导致某些插件失效
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default is 10
  priority: 10
