# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: アストルファの幻想郷
subtitle: こんにちは
description:
author: アストルファ
language:
  - en
  - ja
  - zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://Asutorufa.github.io/
root: /
permalink: posts/:abbrlink/ #:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

syntax_highlighter: prismjs
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 1
  tab_replace: "  "
highlight:
  line_number: true
  auto_detect: false
  tab_replace: "  "
  wrap: true
  hljs: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: categorized ##uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs:https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: #repository:
      github: https://gh_token@github.com/Asutorufa/Asutorufa.github.io.git
    branch: master

#站内搜索
search:
  path: search.xml
  field: post
  format: html

#站内地图
sitemap:
  path: sitemap.xml
  template:
  rel: true
  tags: true
  categories: true

# abbrlink config
abbrlink:
  alg: crc32 #support crc16(default) and crc32
  rep: hex #support dec(default) and hex

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

markdown:
  preset: "default"
  render:
    html: true
    xhtmlOut: false
    langPrefix: "language-"
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  enable_rules:
  disable_rules:
  plugins:
    - name: "@renbaoshuo/markdown-it-katex"
      options:
        skipDelimitersCheck: true
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: false
    permalinkClass: "header-anchor"
    permalinkSide: "left"
    permalinkSymbol: "¶"
    case: 0
    separator: "-"
  images:
    lazyload: true
    prepend_root: false
    post_asset: false
  inline: false # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline

